2020-05-18 21:04:53,307 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 21:04:57,544 ERROR: Exception on /explore [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\learning\microblog\app\routes.py", line 136, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "D:\learning\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "D:\learning\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\learning\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\learning\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "D:\learning\microblog\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-18 21:05:21,115 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 21:05:39,102 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 21:06:40,894 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 21:07:22,785 ERROR: Exception on /explore [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\learning\microblog\app\routes.py", line 136, in explore
    return render_template('index.html', title='Explore', posts=posts)
  File "D:\learning\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "D:\learning\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\learning\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\learning\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "D:\learning\microblog\app\templates\index.html", line 6, in block "content"
    {{ form.hidden_tag() }}
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 471, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'form' is undefined
2020-05-18 21:17:42,386 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 22:27:14,785 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 22:33:42,360 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 22:43:07,126 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 22:43:17,280 ERROR: Exception on /index [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\venv\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\learning\microblog\app\routes.py", line 28, in index
    return render_template('index.html', title='Home', form=form,
  File "D:\learning\microblog\venv\lib\site-packages\flask\templating.py", line 137, in render_template
    return _render(
  File "D:\learning\microblog\venv\lib\site-packages\flask\templating.py", line 120, in _render
    rv = template.render(context)
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 1090, in render
    self.environment.handle_exception()
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\environment.py", line 832, in handle_exception
    reraise(*rewrite_traceback_stack(source=source))
  File "D:\learning\microblog\venv\lib\site-packages\jinja2\_compat.py", line 28, in reraise
    raise value.with_traceback(tb)
  File "D:\learning\microblog\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "D:\learning\microblog\app\templates\base.html", line 31, in top-level template code
    {% block content %}{% endblock %}
  File "D:\learning\microblog\app\templates\index.html", line 18, in block "content"
    {% for post in posts %}
TypeError: 'Pagination' object is not iterable
2020-05-18 22:44:43,784 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 22:46:34,405 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:47]
2020-05-18 23:04:16,925 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:49]
2020-05-19 00:04:44,021 INFO: Microblog startup [in D:\learning\microblog\app\__init__.py:49]
2020-05-19 00:08:24,862 ERROR: Exception on /reset_password_request [GET] [in D:\learning\microblog\venv\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\learning\microblog\venv\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\learning\microblog\venv\lib\site-packages\flask\app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\learning\microblog\app\routes.py", line 161, in reset_password_request
    form = ResetPasswordRequestForm()
NameError: name 'ResetPasswordRequestForm' is not defined
